//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales
    {
        public int ID { get; set; }
        public int Customer_ID { get; set; }
        public int Product_ID { get; set; }
        public string PaymentType { get; set; }
        public int Amount { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual Product_ Product_ { get; set; }
    }
}
